### ISSUE TITLE
polymer build es5

### ISSUE THREAD

**Issue by YuriyBishko** [PolymerLabs/amp-viewer#6]
Hello.

When you try open es5-bundled version of Polymer app, get the next error in console:
```
Uncaught TypeError: Illegal invocation
  at CustomElementRegistry.value 
```
Any suggestion how to solve it ?
Thanks!

**Comment by keanulee** [comment]
The Custom Element standard required element definitions to be es6/2015 classes so you need an adapter to convert the es5 function/prototype to an es6 class. For more information see the README on the webcomponents polyfill: https://github.com/webcomponents/custom-elements#es5-vs-es2015
